/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteRouteImport } from './routes/_admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminAuthRouteRouteImport } from './routes/_admin/_auth/route'
import { Route as AdminLoginIndexRouteImport } from './routes/_admin/login/index'
import { Route as AdminAuthExampleTableIndexRouteImport } from './routes/_admin/_auth/example/table/index'
import { Route as AdminAuthExampleModalIndexRouteImport } from './routes/_admin/_auth/example/modal/index'
import { Route as AdminAuthExampleFormIndexRouteImport } from './routes/_admin/_auth/example/form/index'

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthRouteRoute = AdminAuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginIndexRoute = AdminLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuthExampleTableIndexRoute =
  AdminAuthExampleTableIndexRouteImport.update({
    id: '/example/table/',
    path: '/example/table/',
    getParentRoute: () => AdminAuthRouteRoute,
  } as any)
const AdminAuthExampleModalIndexRoute =
  AdminAuthExampleModalIndexRouteImport.update({
    id: '/example/modal/',
    path: '/example/modal/',
    getParentRoute: () => AdminAuthRouteRoute,
  } as any)
const AdminAuthExampleFormIndexRoute =
  AdminAuthExampleFormIndexRouteImport.update({
    id: '/example/form/',
    path: '/example/form/',
    getParentRoute: () => AdminAuthRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login/': typeof AdminLoginIndexRoute
  '/example/form/': typeof AdminAuthExampleFormIndexRoute
  '/example/modal/': typeof AdminAuthExampleModalIndexRoute
  '/example/table/': typeof AdminAuthExampleTableIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof AdminLoginIndexRoute
  '/example/form': typeof AdminAuthExampleFormIndexRoute
  '/example/modal': typeof AdminAuthExampleModalIndexRoute
  '/example/table': typeof AdminAuthExampleTableIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteRouteWithChildren
  '/_admin/_auth': typeof AdminAuthRouteRouteWithChildren
  '/_admin/login/': typeof AdminLoginIndexRoute
  '/_admin/_auth/example/form/': typeof AdminAuthExampleFormIndexRoute
  '/_admin/_auth/example/modal/': typeof AdminAuthExampleModalIndexRoute
  '/_admin/_auth/example/table/': typeof AdminAuthExampleTableIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login/'
    | '/example/form/'
    | '/example/modal/'
    | '/example/table/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/example/form' | '/example/modal' | '/example/table'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_admin/_auth'
    | '/_admin/login/'
    | '/_admin/_auth/example/form/'
    | '/_admin/_auth/example/modal/'
    | '/_admin/_auth/example/table/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/_auth': {
      id: '/_admin/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminAuthRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/login/': {
      id: '/_admin/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof AdminLoginIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/_auth/example/table/': {
      id: '/_admin/_auth/example/table/'
      path: '/example/table'
      fullPath: '/example/table/'
      preLoaderRoute: typeof AdminAuthExampleTableIndexRouteImport
      parentRoute: typeof AdminAuthRouteRoute
    }
    '/_admin/_auth/example/modal/': {
      id: '/_admin/_auth/example/modal/'
      path: '/example/modal'
      fullPath: '/example/modal/'
      preLoaderRoute: typeof AdminAuthExampleModalIndexRouteImport
      parentRoute: typeof AdminAuthRouteRoute
    }
    '/_admin/_auth/example/form/': {
      id: '/_admin/_auth/example/form/'
      path: '/example/form'
      fullPath: '/example/form/'
      preLoaderRoute: typeof AdminAuthExampleFormIndexRouteImport
      parentRoute: typeof AdminAuthRouteRoute
    }
  }
}

interface AdminAuthRouteRouteChildren {
  AdminAuthExampleFormIndexRoute: typeof AdminAuthExampleFormIndexRoute
  AdminAuthExampleModalIndexRoute: typeof AdminAuthExampleModalIndexRoute
  AdminAuthExampleTableIndexRoute: typeof AdminAuthExampleTableIndexRoute
}

const AdminAuthRouteRouteChildren: AdminAuthRouteRouteChildren = {
  AdminAuthExampleFormIndexRoute: AdminAuthExampleFormIndexRoute,
  AdminAuthExampleModalIndexRoute: AdminAuthExampleModalIndexRoute,
  AdminAuthExampleTableIndexRoute: AdminAuthExampleTableIndexRoute,
}

const AdminAuthRouteRouteWithChildren = AdminAuthRouteRoute._addFileChildren(
  AdminAuthRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminAuthRouteRoute: typeof AdminAuthRouteRouteWithChildren
  AdminLoginIndexRoute: typeof AdminLoginIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAuthRouteRoute: AdminAuthRouteRouteWithChildren,
  AdminLoginIndexRoute: AdminLoginIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
